### ISSUE TITLE
Feature Request: Exempting users by private messaging the bot or in the channel !

### ISSUE THREAD

**Issue by vivekjoshy** [ircd-hybrid/hopm#11]
Hi,
Although this is technically not an issue, it would be a nice feature to have and people would happy to use it. Being able to exempt user from scans or add them to a list based on Vhost would be a great feature to have. I started facing this problem when i wanted to exempt some user and saw that i had to edit the hopm.conf file on all servers which is a lot in my case.

Something like:
`!all exempt add nickname`

Maybe:
`!all exempt vhost add testwebsite.com`

And maybe even:
`!all exempt ip 127.0.0.1`

Thanks in advance ^_^

**Comment by miwob** [comment]
Won't be implemented as this would allow every irc-operator (thinking of hostile ones) to add exempts without the knowledge of the HOPM admin.
