### ISSUE TITLE
Request: CTCP Version Reply. 

### ISSUE THREAD

**Issue by Az0nic** [ircd-hybrid/hopm#12]
To allow HOPM to send ctcp version to users apon connection, and then
logs the reply. 

So admins could monitor it with something like the following:
tail -f bopm.log | grep "CTCP VERSION REPLY".

**Comment by Techman** [comment]
A statistics service might be better suited for this, though. If you use Anope 2, there's already a stats system available as a module.

**Comment by miwob** [comment]
That's not planned and will not be implemented.
