### ISSUE TITLE
Hopm Help

### ISSUE THREAD

**Issue by fLayer012** [ircd-hybrid/hopm#17]
Hi im wondering if you can add muaf port in hopm bots latest version.i would like to move the web users out of muaf port if any type of Attack takes place.thank you

**Comment by miwob** [comment]
say what?

**Comment by fLayer012** [comment]
You can make an exempt port so that users can enter chat conversation

hopm..

**Comment by fLayer012** [comment]
Sorry For my bad english. I was just wondering, can we add except ports for hopm? I mean like when somebody connect 7002 hopm will not do anything. Something like that i was trying to say.

**Comment by Adam-** [comment]
Just don't scan port 7002?

**Comment by fLayer012** [comment]
One, two, three doesnt matter. Multiple ports in conf like { except ports "7000"; "7001"; etc. Can we do something like this?
Thanks

**Comment by miwob** [comment]
HOPM does not know to which ircd port the client connects.
