### ISSUE TITLE
Typical nick auto-complete won't trigger a command after commit 1ecde47

### ISSUE THREAD

**Issue by genius3000** [ircd-hybrid/hopm#20]
I just updated to the master branch (latest commit 24a10c4) and noticed no response from the bot in channel using the format: 
`botnick: check blah.blah`
`botnick: stats`
Tested two other formats:
`botnick stats`
`!all stats`
Both worked, realizing that the ":" was causing it to fail.

Looks like this happened in [commit 1ecde47](https://github.com/ircd-hybrid/hopm/commit/1ecde472540ff2a7d60b802d5b78697fe35a9843).
Previously ",", ":", " " were all allowed at the end of the bot's nickname. These are typical suffixes of client auto-completes and would be nice to allow the "," and ":" again.

**Comment by miwob** [comment]
Indeed these got lost during the rewrite. Thanks for pointing out.
