### ISSUE TITLE
not banning?

### ISSUE THREAD

**Issue by DarkTexas** [ircd-hybrid/hopm#25]
Hey, I didn't know where else I could contact you guys, didn't find anyone on #ircd-coders!

HOPM is running and somy proxys are giving bits back once scanned; but HOPM doesn't ban them, is there a way you assist me? I can't find the problem.

[2018-02-28T23:17:29+0100] SCAN -> Negotiation failed 97.107.138.109:80 (HTTP) [default] (523 bytes read)

..but not doing anything..??

**Comment by genius3000** [comment]
According to the [reference config](https://github.com/ircd-hybrid/hopm/blob/905a6b94805b0764f3f7b4a1875af50332e74f47/doc/reference.conf#L495...L499), `Negotiation failed ` means the proxy is not open. HOPM only bans when the proxy is found to be open (public access).
