### ISSUE TITLE
Doesn't seem to be catching definitely known open proxies?

### ISSUE THREAD

**Issue by eskimo** [ircd-hybrid/hopm#26]
For example, these IP's

178.162.222.100
46.48.134.74
186.1.180.70
118.174.170.38
119.28.129.49

Quick google search returns proxy lists with these in them, and the ports seem to be common ports that HOPM should be checking, yet HOPM returns with nothing for them?

**Comment by miwob** [comment]
Most of the proxies you find on these lists can't be used to establish an irc session. HOPM only detects proxies that definitely can be used to establish a connection to the irc server in question.

**Comment by eskimo** [comment]
Yeah, the thing is, these ips are proxies and were used to connect to my network and hopm didn't detect thme for whatever reason.
