### ISSUE TITLE
Permission denied on creating log file causes hopm to exit silently

### ISSUE THREAD

**Issue by jlu5** [ircd-hybrid/hopm#31]
On my system with Debian 9/stretch, I'm experiencing an odd issue where hopm is only usable with the `-d` option. Without it, instead of forking, hopm exits silently with code 0. ~~A gdb analysis tells me that it's "failing" the check in [main.c:147](https://github.com/ircd-hybrid/hopm/blob/de41d9fc3eb46a21c8019420e4a1e7f9da84db51/src/main.c#L147-L148)~~

~~If it's of any use, I configured hopm commit de41d9fc3eb46a21c8019420e4a1e7f9da84db51 using `CFLAGS=-g ./configure --enable-assert --prefix=/usr/local`. Let me know if any other details can be useful.~~

edit: running `strace -f hopm` gave more useful output https://gist.github.com/jlu5/0697f858f50144841a9e1e04227672c7

```
-snip-
close(0)                                = 0
close(1)                                = 0
close(2)                                = 0
open("/usr/local/var/log/hopm.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = -1 EACCES (Permission denied)
dup(2)                                  = -1 EBADF (Bad file descriptor)
write(2, "Cannot open log file. Aborting.:"..., 51) = -1 EBADF (Bad file descriptor)
exit_group(1)                           = ?
+++ exited with 1 +++
```

It appears that hopm tries to log the "cannot open log file" error to stderr, but it already closed stderr.

**Comment by miwob** [comment]
Should be fixed now with 0e8fc2b.
