### ISSUE TITLE
 Negotiation failed on verified and working proxy

### ISSUE THREAD

**Issue by H7-25** [ircd-hybrid/hopm#33]
I'm doing some test using https://github.com/AnonProgrammers/IRC-Flooder and this free http proxy list https://awmproxy.net/freeproxy.php.
Most of proxy are recognized from dnslbl but if i disable it (for test pourpose) most of them are not recognized from hopm scanner
I've try also using manual scan on single ip (so without the flood)  with the same result.
I've try to increase timeout but nothing change.
I'm using inetd on port 6670 and this is my test scanner configuration  :

scanner {
        name = "proxy";

        protocol = HTTP:8080;

        fd = 40000;

        max_read = 4 kbytes;

        timeout = 30 seconds;

        target_ip = "XXXXXXXXXXX";
        target_port = 6670;
        target_string = "Proxy Check";
};

Obviously i've tested with the configured port.

**Comment by miwob** [comment]
Technical support issue. Please seek for help on irc.ircd-hybrid.org if the issue persists.
