### ISSUE TITLE
 DNSBL -> Lookup result for  (18.81.33.39.rbl.efnetrbl.org) 0.0.0.0 (error: 3)

### ISSUE THREAD

**Issue by demonken** [ircd-hybrid/hopm#34]
DNSBL -> Lookup result for Dr_Bilal!Mibbit@39.33.81.18 (18.81.33.39.rbl.efnetrbl.org) 0.0.0.0 (error: 3)

**Comment by demonken** [comment]
its scanning but giving this error and its not banning any proxies

**Comment by miwob** [comment]
Technical support issue. Please seek for help on irc.ircd-hybrid.org if the issue persists.
