### ISSUE TITLE
unrealircd + Hopm

### ISSUE THREAD

**Issue by kh262** [ircd-hybrid/hopm#37]
Hi, I m running an IRCD based on unrealircd and tried to install HOPM also till here is fine 

HOPM is connecting to my IRC server however does not support SSL ports +6697, however, works in 6667 but IRCD won't give oper with the following Error 

Failed OPER attempt by nickname (usernam@IP) [not using SSL/TLS]

	/*
	 * Port of the above server to connect to. This is what HOPM uses to
	 * get onto IRC itself, it is nothing to do with what ports/protocols
	 * are scanned, nor do you need to list every port your ircd listens
	 * on.
	 */
	port = +6697;

appreciate your kind replay 

Thanks

**Comment by miwob** [comment]
HOPM currently doesn't support TLS connections.
