### ISSUE TITLE
Issue with hopm.conf

### ISSUE THREAD

**Issue by KeiroD** [ircd-hybrid/hopm#4]
This is the result I get when I try `./hopm`:

```
[2015-10-12T04:46:16+0000] CONFIG -> Loading /home/example/hopm/etc/hopm.conf
[2015-10-12T04:46:16+0000] CONFIG -> syntax error: line 451
```

See: http://wolf.furryavalon.net/hopm.txt because it looks fine to me?

**Comment by binki** [comment]
It looks like you accidentally commented out line 428 (shown with three lines of context):

```
     * proxies will be reported.
     */
#   sendmail = "/usr/sbin/sendmail";
#};


/*
```

Try replacing `#};` with `};`.

**Comment by KeiroD** [comment]
Ah, my thanks.
