### ISSUE TITLE
On successful scan hit, execute custom command

### ISSUE THREAD

**Issue by GTAXL** [ircd-hybrid/hopm#44]
Hello, I have another feature request. On a successful scanner hit, whether it be open proxy, vulnerable ssh, etc. execute a command on the shell. This would be very useful than having to parse HOPM log files or utilizing sending e-mails. We operate a DNSBL and would love to simplify this process. Allow say $ip and $reason variables to be passed as arguments to the command.

`scan_command = "/home/gtaxl/dnsbl/gnbl.sh add $ip Open Proxy Found! $reason";`

HOPM would execute via the command line as such,
/home/gtaxl/dnsbl/gnbl.sh add 1.2.3.4 Open Proxy Found! SOCKS5:1080
/home/gtaxl/dnsbl/gnbl.sh add 2.3.4.5 Open Proxy Found! HTTP:8080

Having it pass the proxy type and port for the reason would be very useful for the user to identify where the issue is, fix it, and request removal from our DNSBL.

Note! Don't reverse the IP order in the $ip variable, just pass the normal IP, our script, and other's scripts should be setup to reverse the IP order. :)

**Comment by miwob** [comment]
Such a feature is not planned.
