### ISSUE TITLE
Sample working output?

### ISSUE THREAD

**Issue by KeiroD** [ircd-hybrid/hopm#5]
Not really an issue, more of a request.

Can we get examples of a working setup? ie, let's say you have `hopm` working but you want to see sample output that `hopm` would make.

For example, now that I have my hopm working, I don't really have an easy way of testing to make sure that hopm actually _scans_ for proxies and correctly gets rid of them. Maybe offer a way of doing limited testing?

I've obviously done a check on my own IP but, as this is an extremely small network, I don't exactly have a large enough sample to confirm for sure myself that `hopm` is working as it should be. I know the sample configs in `reference.conf` is a working sample but... as they say, seeing is believing, yeah?

Similar to other projects showing off screenshots of what you should expect when you get their project working.

**Comment by miwob** [comment]
You can run the hopm executable with -ddd for maximum verbosity level to see if catches, scans, and possibly k-lines IP addresses properly upon client connect.
