### ISSUE TITLE
Includes, either Local or Remote

### ISSUE THREAD

**Issue by MrBenC** [ircd-hybrid/hopm#8]
Basically, the ability to define something like the following in the main hopm.conf file: .include extra.conf

Use case: When multiple servers are used with one HOPM instance per server (scanning only local connections), it would be nice if I were able to say, have something like ".include blacklist.conf" or ".include opm.conf".  When utilized with rsync, it would make it very easy to keep blacklist settings synchronized between servers.

Ben

**Comment by miwob** [comment]
Conf file includes implemented in 1.1.3
