### ISSUE TITLE
Ports aren't scanned.

### ISSUE THREAD

**Issue by tonigberzosa** [ircd-hybrid/hopm#9]
Hello. I configured HOPM and it doesn't detect proxies on ports. I used the same ports configuration I had on BOPM and BOPM detects the proxies when checking ports but HOPM doesn't. I don't know what's wrong. Any help, please?

**Comment by miwob** [comment]
Please try latest 1.1.2 and see if the issue persists.

**Comment by tonigberzosa** [comment]
Sorry for the delay. I tested it and the issue persists.

**Comment by miwob** [comment]
I think you just have issues with the configuration somewhere. You might want to join our development channel on irc for further assistance.

**Comment by miwob** [comment]
It turned out to be a configuration issue. People please make sure to properly edit your 'target_string'.
